#!/bin/bash
# =============================================================================
# Multi-Layer VPN Server Deployment Script
# Includes: BBR, DNS, Nginx, 3X-UI creds, UFW, fail2ban, backup inbounds,
#           Xray monitoring, split tunneling, geo databases, security hardening
#
# Usage: bash deploy-multilayer.sh
# Idempotent: safe to run multiple times
# =============================================================================

set -euo pipefail

# --------------- Colors & helpers ---------------
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m'

ok()   { echo -e "  ${GREEN}[OK]${NC} $*"; }
warn() { echo -e "  ${YELLOW}[WARN]${NC} $*"; }
fail() { echo -e "  ${RED}[FAIL]${NC} $*"; exit 1; }
step() { echo -e "\n${CYAN}${BOLD}[$1/$TOTAL_STEPS] $2${NC}"; }

TOTAL_STEPS=10
CREDS_FILE="/root/vpn-credentials.txt"
XUI_DB="/etc/x-ui/x-ui.db"
XRAY_BIN_DIR="/usr/local/x-ui/bin"
MONITOR_SCRIPT="/root/monitor-xray.sh"

# Guard: must be root
[[ $EUID -eq 0 ]] || fail "Run as root: sudo bash $0"

echo -e "${BOLD}"
echo "============================================================"
echo "  Multi-Layer VPN Server Deployment"
echo "============================================================"
echo -e "${NC}"

# Initialise credentials file
cat > "$CREDS_FILE" << 'HEADER'
# ============================================================
# VPN Credentials — generated by deploy-multilayer.sh
# Keep this file secure. Delete after copying credentials.
# ============================================================
HEADER
chmod 600 "$CREDS_FILE"

# =============================================================================
# 1. BBR & TCP tuning
# =============================================================================
step 1 "BBR & TCP tuning"

SYSCTL_MARKER="# === VPN Optimization (deploy-multilayer) ==="
if grep -qF "$SYSCTL_MARKER" /etc/sysctl.conf 2>/dev/null; then
    ok "TCP tuning already applied — skipping"
else
    cat >> /etc/sysctl.conf << SYSCTL

$SYSCTL_MARKER
net.core.default_qdisc = fq
net.ipv4.tcp_congestion_control = bbr
net.ipv4.tcp_keepalive_time = 60
net.ipv4.tcp_keepalive_intvl = 10
net.ipv4.tcp_keepalive_probes = 6
net.core.rmem_max = 16777216
net.core.wmem_max = 16777216
net.ipv4.tcp_rmem = 4096 87380 16777216
net.ipv4.tcp_wmem = 4096 65536 16777216
net.ipv4.tcp_fastopen = 3
net.ipv4.tcp_tw_reuse = 1
net.core.somaxconn = 4096
net.ipv4.tcp_max_syn_backlog = 4096
net.ipv4.tcp_slow_start_after_idle = 0
SYSCTL
    sysctl -p > /dev/null 2>&1
    ok "BBR enabled, TCP tuning applied"
fi
echo "  BBR: $(sysctl -n net.ipv4.tcp_congestion_control 2>/dev/null || echo 'n/a')"

# =============================================================================
# 2. DNS (DoT via systemd-resolved)
# =============================================================================
step 2 "DNS configuration"

apt-get install -y systemd-resolved > /dev/null 2>&1 || true

cat > /etc/systemd/resolved.conf << 'DNS'
[Resolve]
DNS=1.1.1.1 8.8.8.8
FallbackDNS=9.9.9.9 8.8.4.4
DNSOverTLS=yes
DNS

systemctl enable systemd-resolved --now 2>/dev/null || true
ok "DNS configured (1.1.1.1 + 8.8.8.8, DoT enabled)"

# =============================================================================
# 3. Nginx camouflage fallback
# =============================================================================
step 3 "Nginx camouflage fallback"

apt-get install -y nginx > /dev/null 2>&1

mkdir -p /var/www/html
cat > /var/www/html/index.html << 'HTML'
<!DOCTYPE html>
<html>
<head><title>Welcome</title></head>
<body>
<h1>It works!</h1>
<p>This is the default web page for this server.</p>
</body>
</html>
HTML

cat > /etc/nginx/sites-available/fallback << 'NGINX'
server {
    listen 127.0.0.1:8081;
    server_name _;
    root /var/www/html;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
NGINX

ln -sf /etc/nginx/sites-available/fallback /etc/nginx/sites-enabled/fallback
rm -f /etc/nginx/sites-enabled/default

if nginx -t 2>/dev/null; then
    systemctl restart nginx
    ok "Nginx listening on 127.0.0.1:8081"
else
    warn "Nginx config test failed — check manually"
fi

# =============================================================================
# 4. 3X-UI panel credentials
# =============================================================================
step 4 "3X-UI panel credentials"

NEW_USER="vpnadm_$(openssl rand -hex 3)"
NEW_PASS="$(openssl rand -base64 16 | tr -d '=/+')"

if command -v x-ui &>/dev/null; then
    x-ui setting -username "$NEW_USER" -password "$NEW_PASS" 2>/dev/null
    ok "Panel credentials updated"
else
    warn "x-ui command not found — credentials generated but not applied"
fi

echo "  User: $NEW_USER"
echo "  Pass: $NEW_PASS"

{
    echo ""
    echo "[3X-UI Panel]"
    echo "Username: $NEW_USER"
    echo "Password: $NEW_PASS"
    echo "Access:   ssh -L 1076:127.0.0.1:1076 root@<server-ip>"
    echo "          then open http://127.0.0.1:1076"
} >> "$CREDS_FILE"

# =============================================================================
# 5. Firewall (UFW)
# =============================================================================
step 5 "Firewall (UFW)"

apt-get install -y ufw > /dev/null 2>&1

ufw default deny incoming  > /dev/null 2>&1
ufw default allow outgoing > /dev/null 2>&1

declare -A UFW_PORTS=(
    [22/tcp]="SSH"
    [80/tcp]="LetsEncrypt"
    [443/tcp]="VLESS Reality main"
    [1076/tcp]="3X-UI Panel (localhost only after hardening)"
    [8443/tcp]="VLESS Reality backup (dl.google.com)"
    [2053/tcp]="VLESS Reality backup (apple.com)"
    [2082/tcp]="VLESS WS Cloudflare"
    [2083/tcp]="VLESS WS Cloudflare alt"
    [10443/tcp]="Reserved backup inbound"
    [10444/tcp]="Reserved backup inbound"
)

for port in "${!UFW_PORTS[@]}"; do
    ufw allow "$port" comment "${UFW_PORTS[$port]}" 2>/dev/null || true
done

echo "y" | ufw enable 2>/dev/null || true
ok "UFW enabled with ports: 22 80 443 1076 8443 2053 2082 2083 10443 10444"

# =============================================================================
# 6. fail2ban
# =============================================================================
step 6 "fail2ban"

apt-get install -y fail2ban > /dev/null 2>&1

cat > /etc/fail2ban/jail.local << 'F2B'
[sshd]
enabled = true
port = 22
maxretry = 3
bantime = 3600
findtime = 600
F2B

systemctl enable fail2ban --now 2>/dev/null || true
ok "fail2ban installed and running"

# =============================================================================
# 7. Xray monitoring cron
# =============================================================================
step 7 "Xray monitoring cron"

cat > "$MONITOR_SCRIPT" << 'MONITOR'
#!/bin/bash
# Xray health monitor — restarts x-ui if xray process is down
LOG="/var/log/xray-monitor.log"

if ! pgrep -x xray > /dev/null 2>&1; then
    echo "$(date '+%Y-%m-%d %H:%M:%S') [ALERT] xray not running — restarting x-ui" >> "$LOG"
    x-ui restart >> "$LOG" 2>&1
    sleep 5
    if pgrep -x xray > /dev/null 2>&1; then
        echo "$(date '+%Y-%m-%d %H:%M:%S') [OK] xray recovered" >> "$LOG"
    else
        echo "$(date '+%Y-%m-%d %H:%M:%S') [CRITICAL] xray still down after restart" >> "$LOG"
    fi
fi
MONITOR

chmod +x "$MONITOR_SCRIPT"

# Add cron if not already present
CRON_LINE="*/5 * * * * /bin/bash $MONITOR_SCRIPT"
if ! crontab -l 2>/dev/null | grep -qF "$MONITOR_SCRIPT"; then
    (crontab -l 2>/dev/null; echo "$CRON_LINE") | crontab -
    ok "Cron job installed: every 5 minutes"
else
    ok "Cron job already exists — skipping"
fi

# =============================================================================
# 8. Geo databases + split tunneling routing
# =============================================================================
step 8 "Geo databases & split-tunneling routing"

mkdir -p "$XRAY_BIN_DIR"

echo "  Downloading geosite.dat ..."
wget -qO "$XRAY_BIN_DIR/geosite.dat" \
    "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geosite.dat" \
    || warn "Failed to download geosite.dat"

echo "  Downloading geoip.dat ..."
wget -qO "$XRAY_BIN_DIR/geoip.dat" \
    "https://github.com/Loyalsoldier/v2ray-rules-dat/releases/latest/download/geoip.dat" \
    || warn "Failed to download geoip.dat"

ok "Geo databases installed in $XRAY_BIN_DIR"

# Apply split-tunneling via x-ui Xray JSON config
# x-ui stores custom xray config; we inject routing rules for Russian domains/IPs
XRAY_CONFIG_PATH="/usr/local/x-ui/bin/config.json"

if [[ -f "$XRAY_CONFIG_PATH" ]]; then
    # Back up existing config
    cp "$XRAY_CONFIG_PATH" "${XRAY_CONFIG_PATH}.bak.$(date +%s)"
fi

# We write the routing block that x-ui's Xray will load.
# Russian traffic goes DIRECT; everything else follows default outbound (proxy/freedom).
# This is written as a template; x-ui merges its own inbound/outbound settings.
# The safest approach: use x-ui's "Xray Settings" -> "Routing Rules" via the DB.
# But since we automate, we write a known-good routing snippet into the x-ui settings table.

if [[ -f "$XUI_DB" ]] && command -v sqlite3 &>/dev/null; then
    # x-ui stores xray template config in the settings table, key = "xrayTemplateConfig"
    ROUTING_CONFIG=$(cat << 'XRAY_JSON'
{
  "log": {
    "loglevel": "warning",
    "access": "/var/log/xray-access.log",
    "error": "/var/log/xray-error.log"
  },
  "api": {
    "tag": "api",
    "services": ["HandlerService", "LoggerService", "StatsService"]
  },
  "stats": {},
  "policy": {
    "levels": {
      "0": {
        "statsUserUplink": true,
        "statsUserDownlink": true
      }
    },
    "system": {
      "statsInboundUplink": true,
      "statsInboundDownlink": true,
      "statsOutboundUplink": true,
      "statsOutboundDownlink": true
    }
  },
  "dns": {
    "servers": [
      "https+local://1.1.1.1/dns-query",
      {
        "address": "https+local://1.1.1.1/dns-query",
        "domains": ["geosite:category-ads-all"],
        "expectIPs": []
      },
      "localhost"
    ],
    "queryStrategy": "UseIPv4"
  },
  "routing": {
    "domainStrategy": "IPIfNonMatch",
    "rules": [
      {
        "inboundTag": ["api"],
        "outboundTag": "api",
        "type": "field"
      },
      {
        "type": "field",
        "outboundTag": "direct",
        "domain": ["geosite:category-ru"]
      },
      {
        "type": "field",
        "outboundTag": "direct",
        "ip": ["geoip:ru"]
      },
      {
        "type": "field",
        "outboundTag": "blocked",
        "domain": ["geosite:category-ads-all"]
      },
      {
        "type": "field",
        "outboundTag": "direct",
        "ip": ["geoip:private"]
      }
    ]
  },
  "inbounds": [],
  "outbounds": [
    {
      "protocol": "freedom",
      "tag": "direct"
    },
    {
      "protocol": "blackhole",
      "tag": "blocked"
    }
  ]
}
XRAY_JSON
)
    # Escape for sqlite: double single quotes
    ROUTING_ESCAPED="${ROUTING_CONFIG//\'/\'\'}"

    # Check if key exists
    EXISTING=$(sqlite3 "$XUI_DB" "SELECT COUNT(*) FROM settings WHERE key='xrayTemplateConfig';" 2>/dev/null || echo "0")
    if [[ "$EXISTING" -gt 0 ]]; then
        sqlite3 "$XUI_DB" "UPDATE settings SET value='${ROUTING_ESCAPED}' WHERE key='xrayTemplateConfig';"
    else
        sqlite3 "$XUI_DB" "INSERT INTO settings (key, value) VALUES ('xrayTemplateConfig', '${ROUTING_ESCAPED}');"
    fi

    ok "Split-tunneling routing configured (RU domains/IPs -> direct)"
else
    warn "sqlite3 or x-ui DB not found — configure routing manually in 3X-UI panel"
fi

# =============================================================================
# 9. Backup Xray inbounds via sqlite3
# =============================================================================
step 9 "Backup Xray inbounds"

if [[ ! -f "$XUI_DB" ]]; then
    warn "x-ui database not found at $XUI_DB — skipping inbound creation"
elif ! command -v sqlite3 &>/dev/null; then
    apt-get install -y sqlite3 > /dev/null 2>&1
fi

if [[ -f "$XUI_DB" ]] && command -v sqlite3 &>/dev/null; then

    # Generate shared cryptographic material
    UUID_8443=$(uuidgen)
    UUID_2053=$(uuidgen)
    UUID_2082=$(uuidgen)

    SUBID_8443=$(openssl rand -hex 8)
    SUBID_2053=$(openssl rand -hex 8)
    SUBID_2082=$(openssl rand -hex 8)

    SHORT_ID_8443=$(openssl rand -hex 8)
    SHORT_ID_2053=$(openssl rand -hex 8)

    WS_PATH="/ws-proxy-$(openssl rand -hex 4)"

    # Generate Reality key pairs via xray
    if command -v xray &>/dev/null; then
        XRAY_CMD="xray"
    elif [[ -x "$XRAY_BIN_DIR/xray" ]]; then
        XRAY_CMD="$XRAY_BIN_DIR/xray"
    else
        XRAY_CMD=""
    fi

    if [[ -n "$XRAY_CMD" ]]; then
        KEYS_8443=$($XRAY_CMD x25519 2>/dev/null)
        PRIV_8443=$(echo "$KEYS_8443" | grep "Private" | awk '{print $3}')
        PUB_8443=$(echo "$KEYS_8443" | grep "Public" | awk '{print $3}')

        KEYS_2053=$($XRAY_CMD x25519 2>/dev/null)
        PRIV_2053=$(echo "$KEYS_2053" | grep "Private" | awk '{print $3}')
        PUB_2053=$(echo "$KEYS_2053" | grep "Public" | awk '{print $3}')
    else
        warn "xray binary not found — using placeholder keys (replace manually!)"
        PRIV_8443="REPLACE_ME_PRIVATE_KEY_8443"
        PUB_8443="REPLACE_ME_PUBLIC_KEY_8443"
        PRIV_2053="REPLACE_ME_PRIVATE_KEY_2053"
        PUB_2053="REPLACE_ME_PUBLIC_KEY_2053"
    fi

    SNIFFING='{"enabled":true,"destOverride":["http","tls"],"metadataOnly":false,"routeOnly":false}'

    # --- Inbound 1: Port 8443 — VLESS Reality (dl.google.com) ---
    SETTINGS_8443=$(cat << EOF
{"clients":[{"id":"${UUID_8443}","flow":"","email":"user-8443@reality","limitIp":0,"totalGB":0,"expiryTime":0,"enable":true,"tgId":"","subId":"${SUBID_8443}","reset":0}],"decryption":"none","fallbacks":[{"dest":"127.0.0.1:8081"}]}
EOF
)

    STREAM_8443=$(cat << EOF
{"network":"tcp","security":"reality","externalProxy":[],"realitySettings":{"show":false,"xver":0,"dest":"dl.google.com:443","serverNames":["dl.google.com"],"privateKey":"${PRIV_8443}","minClient":"","maxClient":"","maxTimeDiff":0,"shortIds":["${SHORT_ID_8443}"],"settings":{"publicKey":"${PUB_8443}","fingerprint":"chrome","serverName":"","spiderX":""}},"tcpSettings":{"acceptProxyProtocol":false,"header":{"type":"none"}}}
EOF
)

    # --- Inbound 2: Port 2053 — VLESS Reality (www.apple.com) ---
    SETTINGS_2053=$(cat << EOF
{"clients":[{"id":"${UUID_2053}","flow":"","email":"user-2053@reality","limitIp":0,"totalGB":0,"expiryTime":0,"enable":true,"tgId":"","subId":"${SUBID_2053}","reset":0}],"decryption":"none","fallbacks":[{"dest":"127.0.0.1:8081"}]}
EOF
)

    STREAM_2053=$(cat << EOF
{"network":"tcp","security":"reality","externalProxy":[],"realitySettings":{"show":false,"xver":0,"dest":"www.apple.com:443","serverNames":["www.apple.com"],"privateKey":"${PRIV_2053}","minClient":"","maxClient":"","maxTimeDiff":0,"shortIds":["${SHORT_ID_2053}"],"settings":{"publicKey":"${PUB_2053}","fingerprint":"chrome","serverName":"","spiderX":""}},"tcpSettings":{"acceptProxyProtocol":false,"header":{"type":"none"}}}
EOF
)

    # --- Inbound 3: Port 2082 — VLESS WebSocket (Cloudflare CDN) ---
    SETTINGS_2082=$(cat << EOF
{"clients":[{"id":"${UUID_2082}","flow":"","email":"user-2082@ws","limitIp":0,"totalGB":0,"expiryTime":0,"enable":true,"tgId":"","subId":"${SUBID_2082}","reset":0}],"decryption":"none","fallbacks":[]}
EOF
)

    STREAM_2082=$(cat << EOF
{"network":"ws","security":"none","externalProxy":[],"wsSettings":{"acceptProxyProtocol":false,"path":"${WS_PATH}","host":"","headers":{}}}
EOF
)

    # Helper: insert inbound if port not already used
    insert_inbound() {
        local port="$1" remark="$2" settings="$3" stream="$4" tag="$5"
        local exists
        exists=$(sqlite3 "$XUI_DB" "SELECT COUNT(*) FROM inbounds WHERE port=$port;" 2>/dev/null || echo "0")
        if [[ "$exists" -gt 0 ]]; then
            warn "Inbound on port $port already exists — skipping (delete manually to recreate)"
            return 0
        fi

        # Escape single quotes for sqlite
        settings="${settings//\'/\'\'}"
        stream="${stream//\'/\'\'}"
        local sniffing_esc="${SNIFFING//\'/\'\'}"

        sqlite3 "$XUI_DB" "INSERT INTO inbounds (user_id, up, down, total, remark, enable, expiry_time, listen, port, protocol, settings, stream_settings, tag, sniffing) VALUES (1, 0, 0, 0, '${remark}', 1, 0, '', ${port}, 'vless', '${settings}', '${stream}', '${tag}', '${sniffing_esc}');"
        ok "Inbound created: $remark (port $port)"
    }

    insert_inbound 8443 "Backup-Reality-Google" "$SETTINGS_8443" "$STREAM_8443" "inbound-8443"
    insert_inbound 2053 "Backup-Reality-Apple"  "$SETTINGS_2053" "$STREAM_2053" "inbound-2053"
    insert_inbound 2082 "Cloudflare-WS"         "$SETTINGS_2082" "$STREAM_2082" "inbound-2082"

    # Save credentials
    {
        echo ""
        echo "[Inbound: Port 8443 — VLESS Reality, SNI: dl.google.com]"
        echo "UUID:       $UUID_8443"
        echo "PublicKey:  $PUB_8443"
        echo "ShortId:    $SHORT_ID_8443"
        echo "SNI:        dl.google.com"
        echo "Fingerprint: chrome"
        echo "SubId:      $SUBID_8443"
        echo ""
        echo "[Inbound: Port 2053 — VLESS Reality, SNI: www.apple.com]"
        echo "UUID:       $UUID_2053"
        echo "PublicKey:  $PUB_2053"
        echo "ShortId:    $SHORT_ID_2053"
        echo "SNI:        www.apple.com"
        echo "Fingerprint: chrome"
        echo "SubId:      $SUBID_2053"
        echo ""
        echo "[Inbound: Port 2082 — VLESS WebSocket (Cloudflare CDN)]"
        echo "UUID:       $UUID_2082"
        echo "WS Path:    $WS_PATH"
        echo "SubId:      $SUBID_2082"
        echo "Note:       Add Cloudflare DNS A record -> server IP, then proxy (orange cloud)"
    } >> "$CREDS_FILE"

else
    warn "Cannot create inbounds — sqlite3 or DB missing"
fi

# =============================================================================
# 10. Security hardening
# =============================================================================
step 10 "Security hardening"

# --- Disable SSH password authentication ---
SSHD_CONFIG="/etc/ssh/sshd_config"
if [[ -f "$SSHD_CONFIG" ]]; then
    # Backup
    cp "$SSHD_CONFIG" "${SSHD_CONFIG}.bak.$(date +%s)" 2>/dev/null || true

    # Disable password auth (idempotent sed)
    sed -i 's/^#*PasswordAuthentication.*/PasswordAuthentication no/' "$SSHD_CONFIG"
    sed -i 's/^#*ChallengeResponseAuthentication.*/ChallengeResponseAuthentication no/' "$SSHD_CONFIG"
    sed -i 's/^#*KbdInteractiveAuthentication.*/KbdInteractiveAuthentication no/' "$SSHD_CONFIG"

    # Ensure PubkeyAuthentication is on
    sed -i 's/^#*PubkeyAuthentication.*/PubkeyAuthentication yes/' "$SSHD_CONFIG"

    # If directives were not present, append them
    grep -q "^PasswordAuthentication" "$SSHD_CONFIG" || echo "PasswordAuthentication no" >> "$SSHD_CONFIG"
    grep -q "^PubkeyAuthentication" "$SSHD_CONFIG"   || echo "PubkeyAuthentication yes" >> "$SSHD_CONFIG"

    systemctl restart sshd 2>/dev/null || systemctl restart ssh 2>/dev/null || true
    ok "SSH password auth disabled (key-only access)"
else
    warn "sshd_config not found"
fi

# --- Restrict 3X-UI panel to localhost ---
# x-ui stores listen address in settings; set it to 127.0.0.1
if [[ -f "$XUI_DB" ]] && command -v sqlite3 &>/dev/null; then
    # The x-ui settings table has key "webListen" for the bind address
    EXISTING_LISTEN=$(sqlite3 "$XUI_DB" "SELECT COUNT(*) FROM settings WHERE key='webListen';" 2>/dev/null || echo "0")
    if [[ "$EXISTING_LISTEN" -gt 0 ]]; then
        sqlite3 "$XUI_DB" "UPDATE settings SET value='127.0.0.1' WHERE key='webListen';"
    else
        sqlite3 "$XUI_DB" "INSERT INTO settings (key, value) VALUES ('webListen', '127.0.0.1');"
    fi
    ok "3X-UI panel restricted to localhost (use SSH tunnel to access)"
    echo "  Access: ssh -L 1076:127.0.0.1:1076 root@<server-ip>"
else
    warn "Cannot restrict panel — configure webListen=127.0.0.1 manually"
fi

# =============================================================================
# Restart x-ui to apply all changes
# =============================================================================
echo ""
echo -e "${CYAN}${BOLD}Restarting x-ui to apply changes...${NC}"
if command -v x-ui &>/dev/null; then
    x-ui restart 2>/dev/null || true
    sleep 3
    ok "x-ui restarted"
else
    warn "x-ui command not found — restart manually"
fi

# =============================================================================
# Final summary
# =============================================================================
echo ""
echo -e "${BOLD}============================================================"
echo "  DEPLOYMENT COMPLETE"
echo "============================================================${NC}"
echo ""
echo -e "${GREEN}Services:${NC}"
echo "  BBR:       $(sysctl -n net.ipv4.tcp_congestion_control 2>/dev/null || echo 'n/a')"
echo "  Nginx:     $(systemctl is-active nginx 2>/dev/null || echo 'n/a')"
echo "  UFW:       $(ufw status | head -1 2>/dev/null || echo 'n/a')"
echo "  fail2ban:  $(systemctl is-active fail2ban 2>/dev/null || echo 'n/a')"
echo "  x-ui:      $(systemctl is-active x-ui 2>/dev/null || echo 'check: x-ui status')"
echo ""
echo -e "${GREEN}Credentials saved to:${NC} $CREDS_FILE"
echo ""
echo -e "${YELLOW}Display credentials now:${NC}"
cat "$CREDS_FILE"
echo ""
echo -e "${BOLD}NEXT STEPS:${NC}"
echo "  1. Copy SSH key to server BEFORE logout (password auth is now disabled!)"
echo "     ssh-copy-id root@<server-ip>"
echo "  2. Access 3X-UI panel via SSH tunnel:"
echo "     ssh -L 1076:127.0.0.1:1076 root@<server-ip>"
echo "     Open: http://127.0.0.1:1076"
echo "  3. For Cloudflare WS inbound (port 2082):"
echo "     - Add DNS A record pointing to server IP"
echo "     - Enable Cloudflare proxy (orange cloud)"
echo "     - In Cloudflare: SSL/TLS -> Full"
echo "  4. On client (Hiddify): enable fragmentation (tlshello, 1-3, 1-3)"
echo "  5. Test all inbounds: 443, 8443, 2053, 2082"
echo ""
